// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mxygem/firehose-abuse-scanner/internal/models"
	"github.com/mxygem/firehose-abuse-scanner/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorer creates a new instance of MockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorer {
	mock := &MockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorer is an autogenerated mock type for the Storer type
type MockStorer struct {
	mock.Mock
}

type MockStorer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorer) EXPECT() *MockStorer_Expecter {
	return &MockStorer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStorer
func (_mock *MockStorer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStorer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStorer_Expecter) Close() *MockStorer_Close_Call {
	return &MockStorer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStorer_Close_Call) Run(run func()) *MockStorer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorer_Close_Call) Return(err error) *MockStorer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_Close_Call) RunAndReturn(run func() error) *MockStorer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// InsertEvent provides a mock function for the type MockStorer
func (_mock *MockStorer) InsertEvent(ctx context.Context, e models.FirehoseEvent) error {
	ret := _mock.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for InsertEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FirehoseEvent) error); ok {
		r0 = returnFunc(ctx, e)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_InsertEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertEvent'
type MockStorer_InsertEvent_Call struct {
	*mock.Call
}

// InsertEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - e models.FirehoseEvent
func (_e *MockStorer_Expecter) InsertEvent(ctx interface{}, e interface{}) *MockStorer_InsertEvent_Call {
	return &MockStorer_InsertEvent_Call{Call: _e.mock.On("InsertEvent", ctx, e)}
}

func (_c *MockStorer_InsertEvent_Call) Run(run func(ctx context.Context, e models.FirehoseEvent)) *MockStorer_InsertEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FirehoseEvent
		if args[1] != nil {
			arg1 = args[1].(models.FirehoseEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_InsertEvent_Call) Return(err error) *MockStorer_InsertEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_InsertEvent_Call) RunAndReturn(run func(ctx context.Context, e models.FirehoseEvent) error) *MockStorer_InsertEvent_Call {
	_c.Call.Return(run)
	return _c
}

// InsertFlagged provides a mock function for the type MockStorer
func (_mock *MockStorer) InsertFlagged(ctx context.Context, r storage.FlaggedRecord) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for InsertFlagged")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.FlaggedRecord) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorer_InsertFlagged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertFlagged'
type MockStorer_InsertFlagged_Call struct {
	*mock.Call
}

// InsertFlagged is a helper method to define mock.On call
//   - ctx context.Context
//   - r storage.FlaggedRecord
func (_e *MockStorer_Expecter) InsertFlagged(ctx interface{}, r interface{}) *MockStorer_InsertFlagged_Call {
	return &MockStorer_InsertFlagged_Call{Call: _e.mock.On("InsertFlagged", ctx, r)}
}

func (_c *MockStorer_InsertFlagged_Call) Run(run func(ctx context.Context, r storage.FlaggedRecord)) *MockStorer_InsertFlagged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.FlaggedRecord
		if args[1] != nil {
			arg1 = args[1].(storage.FlaggedRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorer_InsertFlagged_Call) Return(err error) *MockStorer_InsertFlagged_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorer_InsertFlagged_Call) RunAndReturn(run func(ctx context.Context, r storage.FlaggedRecord) error) *MockStorer_InsertFlagged_Call {
	_c.Call.Return(run)
	return _c
}
